### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by iwfu** [Vinz87/TndrAssistant#8]
python TndrAssistant.py

2017-01-30 00:32:34	list indices must be integers, not str
Traceback (most recent call last):
  File "TndrAssistant.py", line 118, in <module>
    users = [result["user"] for result in api_res["results"]]
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "TndrAssistant.py", line 126, in <module>
    console_logger.debug("# users: %s", len(users))
NameError: name 'users' is not defined

i don't know what to do? 
ps: can you add in the readme, some instructions to config the ifttt mail stuff please

**Comment by iwfu** [comment]
for the error, it was an old version, it works now.

**Comment by Vinz87** [comment]
that's correct.

for the email notification, the only thing you have to set in config.py file is the SMTP_SERVER (for Gmail is "smtp.gmail.com"), your email as NOTIFICATIONS_EMAIL and the password (Gmail requires you to set an application-specific password)

in IFTTT instead sign up for an account, and create an "applet" where the IF part is "receive a web request" from the Maker Channel, and the THEN part is a Notification. you will then copy the Maker Channel key you will be assigned in the config.py file.

Anyway, you'll probably find more useful the email notification since it includes pictures of the match candidate ;)
